# Generated by Django 4.1.3 on 2022-11-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idStudent', models.IntegerField()),
                ('topic_selection', models.TextField()),
                ('selecting_sources', models.TextField()),
                ('carrying_reserch', models.TextField()),
                ('shaping_work', models.TextField()),
                ('making', models.TextField()),
                ('defending', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.TextField(max_length=7)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('patronymic', models.TextField()),
            ],
        ),
    ]
